{
 "title": "Kubernetes / Compute Resources / Cluster",
 "tags": [
  "infrastructure",
  "zeus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(count by (`@resource.k8s.cluster.name`) (kube_node_info))"
    }
   },
   {
    "name": "aws_account",
    "query": {
     "query": "query_result(count by (`@aws.account`) (kube_node_info))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Headlines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (`@resource.k8s.namespace.name`))) / sum(kube_node_status_allocatable{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (`@resource.k8s.namespace.name`))) / sum(kube_node_status_allocatable{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum((node_memory_MemAvailable_bytes)) / sum(node_memory_MemTotal_bytes{job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (`@resource.k8s.namespace.name`))) / sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (`@resource.k8s.namespace.name`))) / sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (`@resource.k8s.namespace.name`, `@resource.k8s.pod.name`, `@resource.k8s.container.name`, `@resource.k8s.node.name`))) by (`@resource.k8s.namespace.name`)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "count(avg((max(kube_pod_owner{`@resource.k8s.workload.type`=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (`@resource.k8s.namespace.name`, `@resource.k8s.workload.name`, `@resource.k8s.pod.name`, `@resource.k8s.workload.type`))) by (`@resource.k8s.workload.name`, `@resource.k8s.namespace.name`)) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (`@resource.k8s.namespace.name`, `@resource.k8s.pod.name`, `@resource.k8s.container.name`, `@resource.k8s.node.name`))) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (`@resource.k8s.namespace.name`, `@resource.k8s.pod.name`, `@resource.k8s.container.name`, `@resource.k8s.node.name`))) by (`@resource.k8s.namespace.name`) / sum((sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum((sum(irate(container_cpu_usage_seconds_total[5m])) by (`@resource.k8s.namespace.name`, `@resource.k8s.pod.name`, `@resource.k8s.container.name`, `@resource.k8s.node.name`))) by (`@resource.k8s.namespace.name`) / sum((sum(kube_pod_container_resource_limits{resource=\"cpu\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", container!=\"\"}) by (`@resource.k8s.namespace.name`)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_owner) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "count(avg((max(kube_pod_owner{`@resource.k8s.workload.type`=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (`@resource.k8s.namespace.name`, `@resource.k8s.workload.name`, `@resource.k8s.pod.name`, `@resource.k8s.workload.type`))) by (`@resource.k8s.workload.name`, `@resource.k8s.namespace.name`)) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", container!=\"\"}) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", container!=\"\"}) by (`@resource.k8s.namespace.name`) / sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum((sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", container!=\"\"}) by (`@resource.k8s.namespace.name`) / sum((sum(kube_pod_container_resource_limits{resource=\"memory\"}) by (`@resource.k8s.namespace.name`))) by (`@resource.k8s.namespace.name`)"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__interval])) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__interval])) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__interval])) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__interval])) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__interval])) by (`@resource.k8s.namespace.name`)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__interval])) by (`@resource.k8s.namespace.name`)"
    }
   ]
  },
  {
   "title": "Bandwidth by Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__rate_interval])) by (`@resource.k8s.namespace.name`)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__rate_interval])) by (`@resource.k8s.namespace.name`)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__rate_interval])) by (`@resource.k8s.namespace.name`)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", `@resource.k8s.namespace.name`=~\".+\"}[$__rate_interval])) by (`@resource.k8s.namespace.name`)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IOPS(Reads+Writes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum by(`@resource.k8s.namespace.name`) (rate(container_fs_reads_total{job=\"kubelet\", container!=\"\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", container!=\"\", namespace!=\"\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "ThroughPut(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(`@resource.k8s.namespace.name`) (rate(container_fs_reads_bytes_total{job=\"kubelet\", container!=\"\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", container!=\"\", namespace!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IO - Distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Storage IO",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(`@resource.k8s.namespace.name`) (rate(container_fs_reads_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(`@resource.k8s.namespace.name`) (rate(container_fs_writes_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(`@resource.k8s.namespace.name`) (rate(container_fs_reads_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(`@resource.k8s.namespace.name`) (rate(container_fs_reads_bytes_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(`@resource.k8s.namespace.name`) (rate(container_fs_writes_bytes_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    },
    {
     "expr": "sum by(`@resource.k8s.namespace.name`) (rate(container_fs_reads_bytes_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]) + rate(container_fs_writes_bytes_total{job=\"kubelet\", device=~\"mmcblk.p.+|.*nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\", container!=\"\", namespace!=\"\"}[$__rate_interval]))"
    }
   ]
  }
 ]
}