{
 "title": "Kubernetes / Compute Resources / Workload",
 "tags": [
  "workload",
  "zeus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info, @resource.k8s.cluster.name)"
    }
   },
   {
    "name": "aws_account",
    "query": {
     "query": "label_values(kube_node_info, @aws.account)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{\"@resource.k8s.cluster.name\"=\"$cluster\"}, @resource.k8s.namespace.name)"
    }
   },
   {
    "name": "type",
    "query": {
     "query": "label_values(kube_pod_owner{\"@resource.k8s.namespace.name\"=\"$namespace\"}, @resource.k8s.workload.type)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(kube_pod_owner{\"@resource.k8s.namespace.name\"=\"$namespace\", \"@resource.k8s.workload.type\"=\"$type\"}, @resource.k8s.workload.name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    (sum(irate(container_cpu_usage_seconds_total[5m])) by (@resource.k8s.namespace.name, @resource.k8s.pod.name, @resource.k8s.container.name, @resource.k8s.node.name)){\"@resource.k8s.namespace.name\"=\"$namespace\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    (sum(irate(container_cpu_usage_seconds_total[5m])) by (@resource.k8s.namespace.name, @resource.k8s.pod.name, @resource.k8s.container.name, @resource.k8s.node.name)){\"@resource.k8s.namespace.name\"=\"$namespace\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"cpu\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    (sum(irate(container_cpu_usage_seconds_total[5m])) by (@resource.k8s.namespace.name, @resource.k8s.pod.name, @resource.k8s.container.name, @resource.k8s.node.name)){\"@resource.k8s.namespace.name\"=\"$namespace\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n/sum(\n    kube_pod_container_resource_requests{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"cpu\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"cpu\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    (sum(irate(container_cpu_usage_seconds_total[5m])) by (@resource.k8s.namespace.name, @resource.k8s.pod.name, @resource.k8s.container.name, @resource.k8s.node.name)){\"@resource.k8s.namespace.name\"=\"$namespace\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n/sum(\n    kube_pod_container_resource_limits{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"cpu\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{\"@resource.k8s.namespace.name\"=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{\"@resource.k8s.namespace.name\"=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"memory\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{\"@resource.k8s.namespace.name\"=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n/sum(\n    kube_pod_container_resource_requests{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"memory\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"memory\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{\"@resource.k8s.namespace.name\"=\"$namespace\", container!=\"\", image!=\"\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n/sum(\n    kube_pod_container_resource_limits{ \"@resource.k8s.namespace.name\"=\"$namespace\", resource=\"memory\"}\n  * on(@resource.k8s.namespace.name,@resource.k8s.pod.name)\n    group_left(@resource.k8s.workload.name, @resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}\n) by (@resource.k8s.pod.name)\n"
    }
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Network Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod: Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg(irate(container_network_receive_bytes_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Container Bandwidth by Pod: Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(avg(irate(container_network_transmit_bytes_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Packets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Rate of Received Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_packets_dropped_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_packets_dropped_total{job=\"kubelet\", \"@resource.k8s.namespace.name\"=\"$namespace\"}[$__rate_interval])\n* on (@resource.k8s.namespace.name,@resource.k8s.pod.name)\ngroup_left(@resource.k8s.workload.name,@resource.k8s.workload.type) (max(kube_pod_owner{\"@resource.k8s.workload.type\"=~\"ReplicaSet|StatefulSet|DaemonSet|Job\"}) by (@resource.k8s.namespace.name, @resource.k8s.workload.name, @resource.k8s.pod.name, @resource.k8s.workload.type)){\"@resource.k8s.namespace.name\"=\"$namespace\", workload=~\"$workload\", \"@resource.k8s.workload.type\"=\"$type\"}) by (@resource.k8s.pod.name))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}