apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelb
  # namespace is specified as namespace destination in env/{dev,test,prod}/team-geordie.yaml
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: geordie
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: teams/team-geordie/prod/yelb
    helm:
      values: |
        {{- toYaml .Values | nindent 8 }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true