{
 "title": "Kubernetes / Logs and Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "amp_datasource", "label": "AMP", "query": "prometheus" },
   { "name": "opensearch_datasource", "label": "OpenSearch", "query": "grafana-opensearch-datasource" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values({namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Count per Namespace",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.attributes.k8s@namespace@name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "body:[* TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Count per Namespace",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.attributes.k8s@namespace@name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "body:[* TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Count per Pod",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.attributes.k8s@pod@name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "resource.attributes.k8s@namespace@name:\"$namespace\"\nAND body:[* TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Count per Container",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "resource.attributes.k8s@container@name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "resource.attributes.k8s@namespace@name:\"$namespace\" AND resource.attributes.k8s@pod@name:\"$pod\"\nAND body:[* TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "$namespace / $pod / $container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "resource.attributes.k8s@namespace@name:\"$namespace\"\nAND resource.attributes.k8s@pod@name:\"$pod\"\nAND resource.attributes.k8s@container@name:\"$container\"\nAND body:[* TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Log Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "resource.attributes.k8s@namespace@name:\"$namespace\"\nAND resource.attributes.k8s@pod@name:\"$pod\"\nAND resource.attributes.k8s@container@name:\"$container\"\nAND body:[* TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"}[5m])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes{namespace=\"$namespace\", pod=\"$pod\", container=\"$container\"})",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}