{
 "title": "AMP Workspace Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "LabelSet",
    "label": "LabelSet",
    "query": {}
   },
   {
    "name": "AMPWorkspace",
    "label": "AMPWorkspace",
    "query": {}
   },
   {
    "name": "Account",
    "label": "Account",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Summary - $AMPWorkspace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "AMPWorkspace" },
  {
   "title": "ActiveSeriesLimitPerLabelSet",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "SEARCH('{AWS/Prometheus,LabelSet,Workspace} MetricName=\"ActiveSeriesLimitPerLabelSet\"', 'Average', 300)",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "namespace": "AWS/Prometheus",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/Prometheus", "type": "string" }, "type": "property" },
      "select": { "name": "AVG", "type": "function" }
     },
     "sqlExpression": "SELECT SUM(ActiveSeriesLimitPerLabelSet) FROM SCHEMA(\"AWS/Prometheus\", LabelSet,Workspace) WHERE Workspace = '$AMPWorkspace' GROUP BY LabelSet",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DiscardedSamplesPerLabelSet",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "SELECT AVG(DiscardedSamplesPerLabelSet) FROM SCHEMA(\"AWS/Prometheus\", LabelSet,Reason,Workspace) WHERE Workspace = '$AMPWorkspace' GROUP BY LabelSet",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Discarded Samples by Workspace and Reason",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricName": "DiscardedSamples",
     "metricQueryType": 1,
     "namespace": "AWS/Prometheus",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/Prometheus", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Reason", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "DiscardedSamples", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "$AMPWorkspace" }, "property": { "name": "Workspace", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(DiscardedSamples) FROM \"AWS/Prometheus\" WHERE Workspace = '$AMPWorkspace' GROUP BY Reason",
     "statistic": "Sum"
    }
   ]
  },
  { "title": "LabelSet - $LabelSet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "LabelSet" },
  {
   "title": "ActiveSeriesLimitPerLabelSet",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "SELECT AVG(ActiveSeriesLimitPerLabelSet) FROM SCHEMA(\"AWS/Prometheus\", LabelSet,Workspace) WHERE LabelSet = '$LabelSet' AND Workspace = '$AMPWorkspace'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "ActiveSeriesPerLabelSet",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "namespace": "AWS/Prometheus",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": {
       "name": "SCHEMA",
       "parameters": [
        { "name": "AWS/Prometheus", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "select": { "name": "AVG", "type": "function" }
     },
     "sqlExpression": "SELECT AVG(ActiveSeriesPerLabelSet) FROM SCHEMA(\"AWS/Prometheus\", LabelSet,Workspace) WHERE LabelSet = '$LabelSet'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DiscardedSamplesPerLabelSet",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "SELECT AVG(DiscardedSamplesPerLabelSet) FROM SCHEMA(\"AWS/Prometheus\", LabelSet,Reason,Workspace) WHERE LabelSet = '$LabelSet'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "IngestionRatePerLabelSet",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "SELECT AVG(IngestionRatePerLabelSet) FROM SCHEMA(\"AWS/Prometheus\", LabelSet,Workspace) WHERE LabelSet = '$LabelSet'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "AMP Workspace Insights - $AMPWorkspace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "repeat": "AMPWorkspace"
  },
  {
   "title": "AMP Resource Counts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "Service": "Prometheus" },
     "metricName": "ResourceCount",
     "metricQueryType": 1,
     "namespace": "AWS/Usage",
     "queryMode": "Metrics",
     "region": "default",
     "sql": {
      "from": { "property": { "name": "AWS/Usage", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Resource", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "select": {
       "name": "SUM",
       "parameters": [
        { "name": "ResourceCount", "type": "functionParameter" }
       ],
       "type": "function"
      },
      "where": {
       "expressions": [
        { "operator": { "name": "=", "value": "Prometheus" }, "property": { "name": "Service", "type": "string" }, "type": "operator" },
        { "operator": { "name": "=", "value": "$AMPWorkspace" }, "property": { "name": "ResourceId", "type": "string" }, "type": "operator" }
       ],
       "type": "and"
      }
     },
     "sqlExpression": "SELECT SUM(ResourceCount) FROM \"AWS/Usage\" WHERE Service = 'Prometheus' AND ResourceId = '$AMPWorkspace' GROUP BY Resource",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Query Samples Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "label": "QuerySamplesProcessed",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sqlExpression": "SELECT SUM(QuerySamplesProcessed) FROM SCHEMA(\"AWS/Prometheus\", Workspace) WHERE Workspace = '$AMPWorkspace'",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "AlertManagerAlertsReceived",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "label": "AlertManagerAlertsReceived",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "SELECT SUM(AlertManagerAlertsReceived) FROM SCHEMA(\"AWS/Prometheus\", Workspace) WHERE Workspace = '$AMPWorkspace'",
     "statistic": "Average"
    }
   ]
  }
 ]
}