{
 "title": "AWS Observability Accelerator - AMP Ingestion Dashboard",
 "description": "Dashboard for Amazon Managed Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   { "name": "datasource", "label": "CloudWatch data source", "query": "cloudwatch" },
   {
    "name": "WorkspaceID",
    "query": {}
   },
   { "name": "job", "label": "Prometheus job", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "Top 20 high cardinality metrics",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20, metrics_cardinality:topk20{})",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Top 20 high cardinality metrics",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "topk(20, metrics_cardinality:topk20{})",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Scrape series per job",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "max by (job) (scrape_series_added{job=~\"^$job$\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Series Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 18 },
   "targets": [
    {
     "expression": "SELECT SUM(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'ActiveSeries' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Workspace Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 18 },
   "targets": [
    {
     "expression": "SELECT AVG(ResourceCount) FROM SCHEMA(\"AWS/Usage\", Class,Resource,ResourceId,Service,Type) WHERE Type = 'Resource' AND ResourceId = '$WorkspaceID' AND Resource = 'IngestionRate' AND Service = 'Prometheus' AND Class = 'None'",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Scrape series per job",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(scrape_series_added)", "legendFormat": "scrape_series_added" },
    { "expr": "sum(scrape_samples_scraped)", "legendFormat": "scrape_samples_scraped" }
   ]
  },
  {
   "title": "alerts firing",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by (alertname) (ALERTS{})", "legendFormat": "{{alertname}}" }
   ]
  },
  {
   "title": "metrics variance over time per job",
   "type": "table",
   "description": "Helps finding out variance in samples collected between scrape intervals",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 25 },
   "targets": [
    {
     "expr": "topk(5, max_over_time(scrape_series_added[6m]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}