apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gp2-encrypted-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2-encrypted
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-encryption-app
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /example/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /example
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: gp2-encrypted-pvc