destinationServer: ''
argoNamespace: ''
argoProject: ''

labels:
  env: dev
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/aws-observability/aws-observability-accelerator
    targetRevision: main

  # Thoses default values can be surcharged by Infrastructure as Code
  env: dev
  clusterName: coa-eks-blueprint-cluster # the name of EKS cluster
  blueprint: 'terraform' # cdk | terraform
  karpenterInstanceProfile:
  ingress:
    type: 'alb' # nginx | alb
    host: # empty or your domain like dev.example.com
