apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-carmen
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: team-carmen
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/CarmenAPuccio/GeoLocationAPI
    path: templates
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true