apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanadatasource-cw
  namespace: grafana-operator
spec:
  instanceSelector:
    matchLabels:
      dashboards: "external-grafana"
  datasource:
    name: aws-observability-accelerator-cloudwatch
    type: cloudwatch
    access: server
    isDefault: false
    url: ""
    jsonData:
      'tlsSkipVerify': false
      'timeInterval': "5s"
      "sigV4Auth": true,
      "sigV4AuthType": "ec2_iam_role"
      "sigV4Region": ${AMG_AWS_REGION}
      "customMetricsNamespaces": "ContainerInsights/Prometheus"
      "defaultRegion": ${AMG_AWS_REGION}
      "provisionedBy": "aws-datasource-provisioner-app"
    editable: true
