{
 "title": "Kubernetes / Kube-apiserver (troubleshooting)",
 "description": "EKS/K8s Dashboards for obsessive people",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(apiserver_current_inflight_requests, job)"
    }
   },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"$job\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Terminations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_terminations_total{job=\"$job\",cluster=\"$cluster\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "API Pod Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Secret Cache Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_envelope_encryption_dek_cache_fill_percent{job=\"$job\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Resource Watches",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, max by (resource,group)(apiserver_longrunning_requests{job=\"$job\",cluster=\"$cluster\",verb=\"WATCH\"}))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Unavailable Apiservice",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max by (name)(max_over_time(aggregator_unavailable_apiservice{job=\"$job\",cluster=\"$cluster\"}[$__interval])) > 0.1",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Core API  Request Duration Heatmap",
   "type": "heatmap",
   "description": "I recommend using a recording rules via kube stack prometheus, please note Max Data points and interval",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_duration_seconds_bucket{job=\"$job\",cluster=\"$cluster\",subresource=\"\",verb!=\"WATCH\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Etcd Request Latency",
   "type": "heatmap",
   "description": "All Calls Heatmap to etcd server. Show etcd high level  if etcd is source of slowness. Adding a recording rule will help.",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (le)(increase(etcd_request_duration_seconds_bucket{job=\"$job\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Slowest Requests (P90) - 5min",
   "type": "timeseries",
   "description": " Using recording rules via kube stack prometheus",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(3, cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{job=\"$job\",cluster=\"$cluster\",quantile=\"0.9\", subresource=\"\"})",
     "legendFormat": "{{resource}}.{{group}}: {{verb}} "
    }
   ]
  },
  {
   "title": "Total inflight request",
   "type": "timeseries",
   "description": "Request rate by error code",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance)(max_over_time(apiserver_current_inflight_requests{job=\"$job\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "% Client Error Rate - 2m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,code)(increase(rest_client_requests_total{job=\"$job\",cluster=\"$cluster\",code!~\"2..\",code!~\"<error>\"}[$__rate_interval])) > 0",
     "legendFormat": "{{code}} - {{instance}}"
    }
   ]
  },
  {
   "title": "API Server CPU usage in CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Admission Webhook Admission Duration -Top 4",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(4, histogram_quantile(0.90, sum without(instance,type,operation) (increase(apiserver_admission_webhook_admission_duration_seconds_bucket{job=\"$job\",cluster=\"$cluster\"}[$__rate_interval]))))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "apiserver request total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, code_resource:apiserver_request_total:rate5m{cluster=\"$cluster\"})",
     "legendFormat": "{{resource}} - verb: {{verb}} - code: {{code}}"
    }
   ]
  },
  {
   "title": "Max Go Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"$job\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Deprecated Api Usage Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, apiserver_requested_deprecated_apis{job=\"$job\",cluster=\"$cluster\"})",
     "legendFormat": "{{resource}} - {{version}}"
    }
   ]
  },
  { "title": "Advanced Priority and Fairness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Shared concurrency limit by priority group",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max without(instance)(apiserver_flowcontrol_request_concurrency_limit{job=\"$job\",cluster=\"$cluster\"})",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "% of priority level max shares used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * max by (priority_level)(apiserver_flowcontrol_current_executing_requests{job=\"$job\",cluster=\"$cluster\"}) / max by (priority_level) (apiserver_flowcontrol_request_concurrency_limit{job=\"$job\",cluster=\"$cluster\"}) ",
     "legendFormat": "{{priority_level}}"
    }
   ]
  },
  {
   "title": "Top executing requests by Flow",
   "type": "timeseries",
   "description": "Number of requests in initial (for a WATCH) or any (for a non-WATCH) execution stage in the API Priority and Fairness subsystem",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max without (endpoint,namespace,service) (apiserver_flowcontrol_current_executing_requests{job=\"$job\",cluster=\"$cluster\"}))",
     "legendFormat": "Flow: {{flow_schema}} --Priority Level: {{priority_level}} -- {{instance}}"
    }
   ]
  },
  {
   "title": "Time Request was in queue by flowschema (p90) - Top Instance",
   "type": "timeseries",
   "description": "Length of time a request spent waiting in its queue - Max of APIservers",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, max without (instance) (increase(apiserver_flowcontrol_request_wait_duration_seconds_bucket{cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{flow_schema}}"
    }
   ]
  },
  {
   "title": "Rejected Requests -2m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (endpoint,job,namespace,service)(increase(apiserver_flowcontrol_rejected_requests_total{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{flow_schema}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Flowcontrol request execution time p90 - Top Instance",
   "type": "timeseries",
   "description": "Duration of initial stage (for a WATCH) or any (for a non-WATCH) stage of request execution in the API Priority and Fairness subsystem",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, max without (instance) (increase(apiserver_flowcontrol_request_execution_seconds_bucket{job=\"$job\",cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "{{flow_schema}} - {{priority_level}}"
    }
   ]
  },
  {
   "title": "Rate of addition per second",
   "type": "timeseries",
   "description": "Length of queue in the API Priority and Fairness subsystem, as seen by each request after it is enqueued",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "topk(5, sum by (instance,priority_level,flow_schema)(rate(apiserver_flowcontrol_request_queue_length_after_enqueue_count{cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "Flow: {{flow_schema}} --Priority: {{priority_level}} --{{instance}}"
    }
   ]
  }
 ]
}