{
 "title": "EKS Scheduler",
 "tags": [ "Infrastructure" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(scheduler_pending_pods,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pending Pods",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sum_over_time(scheduler_pending_pods[1m]))by (queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduling Attempts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(scheduler_pod_scheduling_attempts_sum[$__rate_interval]) / increase(scheduler_pod_scheduling_attempts_count[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Scheduling Attempts Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scheduler_scheduling_attempt_duration_seconds_sum{}[$__rate_interval]) / rate(scheduler_scheduling_attempt_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{profile}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Preemption Attempts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(scheduler_preemption_attempts_total[$__rate_interval])",
     "legendFormat": "{{profile}} - {{instance}}"
    }
   ]
  }
 ]
}